### ISSUE TITLE
絵文字を含む記事タイトルが文字化けする

### ISSUE THREAD

**Issue by utgwkk** [adventar/adventar#21]
[つくりおき Advent Calendar 2020 - Adventar](https://adventar.org/calendars/5821)の22日目の記事 ([🍤🍤🍤えびマヨ🐴🐴🐴 - #つくりおき](https://tsukurioki.hatenablog.com/entry/ebimayo-umai)) のタイトルが、Adventar上で文字化けしていました。絵文字が `????` に置き換わっているようです。

![image](https://user-images.githubusercontent.com/4530627/102901582-25dbe400-44b1-11eb-99ec-01300b0ca10f.png)

**Comment by hokaccha** [comment]
直しました！
