### ISSUE TITLE
ドキュメントタイトル以外のものが記事タイトルとして収集されてしまう

### ISSUE THREAD

**Issue by wtsnjp** [adventar/adventar#24]
Adventar では，各カレンダーの下の部分に記事の一覧が表示され，そこにリンク先 HTML からスクレイピングしたタイトルや Twitter カードの画像データが掲載されると思います．そこで用いられるタイトルなのですが，必ずしもドキュメント全体のタイトルではない `<title>` 要素の内容が収集されてしまう場合があるようです．

例えば，例年私が投稿する記事の見た目は次のようになってしまいます．

![Screen_Shot_2021-04-02_at_23_44_58](https://user-images.githubusercontent.com/9448125/113426970-2b7d8a00-940f-11eb-8a0d-728fcd64c55c.png)

これは，記事全体のタイトルではなく，その記事で使用している `<svg>` 要素のローカルな `<title>` 要素の内容が反映された結果と考えられます（ちなみに SVG コンテナ要素またはグラフィックス要素内での [title タグ](https://developer.mozilla.org/ja/docs/Web/SVG/Element/title)使用は合法で，アクセシビリティのために推奨されていると思います）．

私は Go 言語を書いたことがないので，以下はすべて推測ですが，おそらく原因箇所は次の部分です．

https://github.com/adventar/adventar/blob/d0e1f742c03cd123f05f17c02b5b492f7d4848ac/api-server/grpc-server/util/site_meta.go#L37-L40

これは単純に HTML 文書内のすべての `<title>` タグをループして，最後に見つかったものの text を取ってくる挙動になっているような気がします．

改善案として，確実にドキュメントタイトルを取得できるように `<head>` タグ内の `<title>` を参照するのはどうでしょうか？

```go
dhead := doc.Find("head")
dtitle := dhead.Find("title")
meta.Title = dtitle.Text() 
```

**Comment by hokaccha** [comment]
直しました！
https://github.com/adventar/adventar/commit/9e6c31c7064c002a6367e815b80ff3c892638dfe

データのほうも更新しておきました。
https://adventar.org/calendars/5111

**Comment by wtsnjp** [comment]
ありがとうございます！
