### ISSUE TITLE
Add a open source license

### ISSUE THREAD

**Issue by irvin** [adventar/adventar#4]
This project is very cool. 

Please add an open-source license to the repo, so other people can fork, use it and contribute back. 

You can check this doc from Github for intro: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by hokaccha** [comment]
Added: https://github.com/adventar/adventar/commit/fa0714e49ea3aa60888532b60b924af0c12bbc80
