### ISSUE TITLE
荒らしの対応とアカウント停止以外の対策について

### ISSUE THREAD

**Issue by Hayao0819** [adventar/adventar#46]
プロジェクトのコードに関するIssueでないこと、お許しください。また、#42 との類似もご容赦ください。

大量のベトナム語のカレンダーが作成されていて、人気のカレンダーを探すのに苦労しています。

そこで、運営によるスパムへの対処に加えて以下の改善を提案してみます。

- Viewer数順による並び替え
- カレンダーの購読（いいね等）機能とそれによる並び替え
- カレンダーの通報
- 参加人数による並び替え（同一アカウントによる複数投稿は1人とカウントする）

お忙しい中申し訳ありませんが検討のほどよろしくおねがいします。

**Comment by hokaccha** [comment]
ご報告ありがとうございます。すぐに対応できるかはわかりませんが、検討してみます。

**Comment by hokaccha** [comment]
スパム記事を一覧から除去しました。手動でフラグをたてているので新規でスパムが発生したら都度対応になりますが、いったんこれで最低限の対応とさせてください。

Viewer順など、人気のカレンダーを探しやすくする機能はよさそうですね。少し実装が大変そうではあるので、もし必要であれば別で issue たててもらえればと思います。
