### ISSUE TITLE
iCal 形式で出力される投稿予定カレンダーの予定(event)を終日(allDay)の予定にしてほしい

### ISSUE THREAD

**Issue by azrsh** [adventar/adventar#48]
Adventar を利用者としても投稿者としても毎年使わせていただいています。ありがとうございます。

Adventar の投稿予定のカレンダーを iCal 形式で出力する機能について要望があります。

現在の実装で出力されるカレンダーには、例えば 2023-01-01 が投稿予定日だとすると、2023-01-01 0:00 開始 2023-01-01 0:00 終了の予定が作成されます。この形の予定だと、カレンダーの表示方法によっては非常に見にくい位置に予定が現れます。
(例えば Web 版の Google Calendar で weekly でカレンダーを表示すると、画面内に予定が表示されないことが多いと思います。)

このカレンダー上で予定として表現されているのはアドベントカレンダーの記事の投稿予定日なので、カレンダー上の予定は終日の予定とすべきだと思います。そこで可能なら投稿予定日の予定を終日の予定として iCal 形式のカレンダーに載せるよう変更して欲しいです。

Adventar の iCal 形式のカレンダーに使っているパッケージ ical-generator の API で言えば以下のフラグを `true` にすることで実現できると思います。

- https://github.com/adventar/adventar/blob/fa0353789c9947e9ba2e48f75684811426340ed9/frontend/server/Ical.ts#L8-L12
- https://sebbo2002.github.io/ical-generator/develop/reference/interfaces/ICalEventData.html#allDay

iCal 形式のファイルレベルでは、予定(VEVENT)の開始(DTSTART)と終了(DTEND)に時刻(DATE-TIME data type)ではなく日付(DATE data type)が入るようにする変更になります。

- https://www.ietf.org/rfc/rfc2445.txt

またこの変更を入れる場合は、iCal 形式のカレンダーの生成に使っているパッケージである ical-generator の v3.0 未満に既知の問題があるため v3.0 以上に更新したほうが良いかもしれません。

- https://github.com/sebbo2002/ical-generator/issues/38
- https://github.com/adventar/adventar/blob/fa0353789c9947e9ba2e48f75684811426340ed9/frontend/package.json#L28

もしこの変更を受け入れてくださる場合はこちらで PR を作成することもできます。よろしくお願いします。

**Comment by hokaccha** [comment]
よさそうです！PRいただけると助かります！

**Comment by hokaccha** [comment]
デプロイ完了しました。動作確認のうえ問題なさそうでしたら close してください 🙏 

```
$ curl -s https://adventar.org/users/1.ics | head -n 20 | grep DT
DTSTAMP:20231113T094337
DTSTART;VALUE=DATE:20121201
DTEND;VALUE=DATE:20121201
```

**Comment by azrsh** [comment]
動作の方を確認しました。対応ありがとうございました！
