### ISSUE TITLE
RSSフィードができない

### ISSUE THREAD

**Issue by shun1y** [adventar/adventar#52]
RSSフィードを使ってslackに記事更新を通知しようとしたところ、エラーが発生しました。
[feed validation service](https://validator.w3.org/feed/)でエラーを確認したところ以下の内容が表示されました。

![image](https://github.com/adventar/adventar/assets/97212053/e9591c23-e147-40bf-868f-a9b1cc863f7d)
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fadventar.org%2Fcalendars%2F8536.rss

ご確認のほどよろしくお願いします

**Comment by utgwkk** [comment]
こちらの問題が再発しているようでした。Slackの `/feed subscribe` コマンドで購読しようとすると以下のようなエラーが発生します。

>Sorry, ‘https://adventar.org/calendars/10156.rss’ doesn’t look like a feed url. Try again?

`<rss version="2.0">` の部分を `<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">` に置換すると購読できるようになるようでした。書き換えたRSSファイルを自分で配信して動作確認しています。

**Comment by suchi** [comment]
[InoReader](https://inoreader.com/)でも今年はFeed登録できなくなっており(昨年登録できていたエントリーも現在はエラーになっています)、同じ原因のようでした。

**Comment by hokaccha** [comment]
直してみました。feed package に `xmlns:dc` を指定できるオプションがなかったので力技ですが... https://github.com/adventar/adventar/commit/e5b2b1195f41aa4e892de4f2888d7241edc060fe

```
$ curl https://adventar.org/calendars/10156.rss
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
    <channel>
        <title>川見てる Advent Calendar 2024</title>
        <link>undefined</link>
        <description>川の写真を貼ったり、川についてお話ししたりします。海や湖、滝、流れなどでも大丈夫です。

- 2020: https://adventar.org/calendars/5418
- 2021: https://adventar.org/calendars/6386

[![Image from Gyazo](https://i.gyazo.com/94823ac8f6985d04b42993875aeb5089.jpg)](https://gyazo.com/94823ac8f6985d04b42993875aeb5089)</description>
        <lastBuildDate>Sat, 30 Nov 2024 15:00:00 GMT</lastBuildDate>
        <docs>https://validator.w3.org/feed/docs/rss2.html</docs>
        <generator>Adventar</generator>
        <item>
            <title><![CDATA[今年見た川 2024 - rebuild-kitashirakawa]]></title>
            <link>https://scrapbox.io/rebuild-kitashirakawa/%E4%BB%8A%E5%B9%B4%E8%A6%8B%E3%81%9F%E5%B7%9D_2024</link>
            <guid>196047</guid>
            <pubDate>Sun, 01 Dec 2024 15:00:00 GMT</pubDate>
            <description><![CDATA[川見てる Advent Calendar 2024 2日目]]></description>
            <dc:creator>nna774</dc:creator>
        </item>
        <item>
            <title><![CDATA[清渓川 - 私が歌川です]]></title>
            <link>https://blog.utgw.net/entry/cheonggyecheon</link>
            <guid>196044</guid>
            <pubDate>Sat, 30 Nov 2024 15:00:00 GMT</pubDate>
            <description><![CDATA[川見てる Advent Calendar 2024 1日目]]></description>
            <dc:creator>うたがわきき</dc:creator>
        </item>
    </channel>
</rss>
```

**Comment by suchi** [comment]
ありがとうございます! InoReaderでは登録できるようになりました。また過去のfeedのエラーもリロードしたところ消えました。

**Comment by utgwkk** [comment]
Slackでフィードを購読できるようになったのを確認しました。対応ありがとうございます!
