### ISSUE TITLE
Helpページのコンテンツが実装にあっていない

### ISSUE THREAD

**Issue by ikeji** [adventar/adventar#53]
こんにちは。
開発ありがとうございます。毎年便利に使わせていただいております。

Helpページに以下の記載があります
```
登録の強制解除
登録日を過ぎても投稿がない場合、カレンダーを作成したユーザーに限り、その登録を削除する権限があります。
削除できるのは、投稿日の翌々日以降です。例えば12/3の登録に対して投稿がない場合、12/5の0時以降は削除可能になります。
```
https://github.com/adventar/adventar/blob/main/frontend/pages/help.vue

しかし、実際はカレンダーのオーナーは時刻によらず、いつでも削除可能であるように見えます。

以下のコミットで、時刻によらずいつでも登録を削除できるように変更されたようです。
https://github.com/adventar/adventar/commit/976a0d701409a0ea820b0041388d66030ae3c968

Helpページの更新抜けかなと思います。
お手数ですが、ご確認よろしくおねがいします。

**Comment by hokaccha** [comment]
ありがとうございます。helpページを直しました。 https://github.com/adventar/adventar/commit/7738c21236eab39ca03169ef3da82b5d503dea84
