### ISSUE TITLE
oEmbedのレスポンスが仕様に合っていない

### ISSUE THREAD

**Issue by r4ai** [adventar/adventar#54]
こんばんは。大変便利なソフトウェアの開発ありがとうございます。
ブログにAdvantarを埋め込もうとした際に、埋め込めない問題に遭遇したため、以下のバグを報告させていただきます。

## 概要

カレンダーに対するoEmbedのレスポンスに、`html`パラメータが含まれていません。

## 例

https://adventar.org/calendars/1 のoEmbedのレスポンスとして、次のJSONが返されます。

```json
{
    "version": "1.0",
    "width": "100%",
    "height": 437,
    "type": "rich",
    "provider_name": "Adventar",
    "provider_url": "https://adventar.org",
    "url": "https://adventar.org/calendars/1/embed"
}
```

ここで、埋め込み用のHTMLは`url`パラメータのリンク先にありますが、oEmbedの仕様を見るとこれはiframeを用いて`html`パラメータとして返すべきだと思われます。`photo` type の場合は、埋め込み用の画像を`url`パラメータで返すことになっていますが、`rich` type の場合は`html`パラメータがrequiredになっているので、少なくともレスポンスに`html`パラメータを含めるべきだと思われます。

> #### 2.3.4.4. The rich type
> This type is used for rich HTML content that does not fall under one of the other categories. The following parameters are defined:
> 
> - `html` (required)
>   The HTML required to display the resource. The HTML should have no padding or margins. Consumers may wish to load the HTML in an off-domain iframe to avoid XSS vulnerabilities. The markup should be valid XHTML 1.0 Basic.
> - `width` (required)
> The width in pixels required to display the HTML.
> - `height` (required)
>   The height in pixels required to display the HTML.
> 
> Responses of this type must obey the `maxwidth` and `maxheight` request parameters.
> https://oembed.com/#section2

**Comment by hokaccha** [comment]
なるほど、note 用に作ったものなのですが仕様をみたしてませんでしたか。動作検証をしたいので、どのブログサービスか教えていただけると助かります。

**Comment by r4ai** [comment]
## 動作検証

私の所属するサークルで開発しているブログ[ricora/alg-blog](https://github.com/ricora/alg-blog)において埋め込めませんでした。現在開発中でありまだデプロイしていないため、ローカルサーバーを立ち上げないと検証できない状態です。一応、

1. `git clone https://github.com/ricora/alg-blog.git`
2. `bun run --bun build && bun run --bun dev`
3. `http://localhost:4321/posts/advent-2022/` にアクセスする

で埋め込めていないことは確認できます。

そのほかのサービスとして、はてなブログもoEmbedによる埋め込みをサポートしていますが、URLから埋め込もうとするとリンクカードとなってしまい埋め込めませんでした。

![image](https://github.com/adventar/adventar/assets/96561881/3ae02568-214b-4dd8-b795-46c0d02d32d3)

正常に埋め込めている例 (https://speakerdeck.com/morganepeng/design-and-strategy-how-to-deal-with-people-who-dont-get-design )：

![image](https://github.com/adventar/adventar/assets/96561881/bb4162ac-b7eb-42ad-8935-240fa619c551)

## 想定されるレスポンス

以下のように、htmlフィールドにurlをsrc属性として持つiframeタグを書くとよいと思われます。

```
{
    "version": "1.0",
    "width": "100%",
    "height": 437,
    "type": "rich",
    "provider_name": "Adventar",
    "provider_url": "https://adventar.org",
    "url": "https://adventar.org/calendars/1/embed",
    "html": "\u003ciframe src=\"//adventar.org/calendars/1/embed\" width=\"100%\" height=\"437\"\u003e\u003c/iframe\u003e\n"
}
```

実際にSpeakerdeckのoEmbed APIでは上記のようなレスポンスが返ってきます。

Speakerdeckのレスポンスの例：https://speakerdeck.com/oembed.json?url=https%3A%2F%2Fspeakerdeck.com%2Fmorganepeng%2Fdesign-and-strategy-how-to-deal-with-people-who-dont-get-design

**Comment by hokaccha** [comment]
https://github.com/adventar/adventar/commit/44e322f62feda5ade32510e2d560de4c556e3ecc で対応してみました。

**Comment by r4ai** [comment]
正常に埋め込められることを確認できました。迅速な対応ありがとうございました。

![image](https://github.com/adventar/adventar/assets/96561881/3973604e-ef8e-4b3d-b192-685318711484)

![image](https://github.com/adventar/adventar/assets/96561881/52bf7394-470b-4c28-bec8-cee570fd3297)
